# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATNetworkDataUsageMacOSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ATNetworkDataUsage', :path => '../../../'
  # Pods for ATNetworkDataUsageMacOSX

  target 'ATNetworkDataUsageMacOSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATNetworkDataUsageMacOSXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
